version: 2
jobs:
  build-frontend:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          working_directory: frontend
          command: npm ci
      - run:
          working_directory: frontend
          command: npm run lint
      - run:
          working_directory: frontend
          command: npm run build

  build-backend:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-backend-deps-{{ checksum "backend/composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-backend-deps-
      - run:
          working_directory: backend
          command: composer install -n --prefer-dist
      - save_cache:
          key: v1-backend-deps-{{ checksum "backend/composer.json" }}
          paths:
            - ./backend/vendor
      - run:
          working_directory: backend
          command: composer test

workflows:
  version: 2
  build:
    jobs:
      - build-frontend
      - build-backend
