services:
  database:
    image: postgres:18@sha256:69e8582b781cb44fa4557b98ed586fe68361e320d9b12f9707494335634f4f3d
    volumes:
      - db:/var/lib/postgresql
    environment:
      POSTGRES_DB: intern
      POSTGRES_USER: intern
      POSTGRES_PASSWORD: secret
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  db:
