/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MatmenyRouteImport } from './routes/matmeny'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as GoogleappsRouteImport } from './routes/googleapps'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as BukkerIndexRouteImport } from './routes/bukker/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as ArrplanIndexRouteImport } from './routes/arrplan/index'
import { Route as UsersRegistrationsRouteImport } from './routes/users/registrations'
import { Route as UserNameRouteImport } from './routes/user/$name'
import { Route as PrinterSisteRouteImport } from './routes/printer/siste'
import { Route as PrinterFakturereRouteImport } from './routes/printer/fakturere'
import { Route as GroupNameRouteImport } from './routes/group/$name'
import { Route as BukkerIdRouteImport } from './routes/bukker/$id'
import { Route as BooksRegisterRouteImport } from './routes/books/register'
import { Route as ArrplanSemesterRouteImport } from './routes/arrplan/$semester'
import { Route as ApiMatmenyIcsRouteImport } from './routes/api/matmeny-ics'
import { Route as BooksIdIndexRouteImport } from './routes/books/$id/index'
import { Route as ApiMatmenyIndexRouteImport } from './routes/api/matmeny/index'
import { Route as DugnadenOldListRouteImport } from './routes/dugnaden/old/list'
import { Route as BooksIdEditRouteImport } from './routes/books/$id/edit'
import { Route as ApiSaml2SlsRouteImport } from './routes/api/saml2/sls'
import { Route as ApiSaml2MetadataRouteImport } from './routes/api/saml2/metadata'
import { Route as ApiSaml2LogoutRouteImport } from './routes/api/saml2/logout'
import { Route as ApiSaml2LoginRouteImport } from './routes/api/saml2/login'
import { Route as ApiSaml2AcsRouteImport } from './routes/api/saml2/acs'
import { Route as ApiMatmenyPlainRouteImport } from './routes/api/matmeny/plain'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MatmenyRoute = MatmenyRouteImport.update({
  id: '/matmeny',
  path: '/matmeny',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleappsRoute = GoogleappsRouteImport.update({
  id: '/googleapps',
  path: '/googleapps',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const BukkerIndexRoute = BukkerIndexRouteImport.update({
  id: '/bukker/',
  path: '/bukker/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrplanIndexRoute = ArrplanIndexRouteImport.update({
  id: '/arrplan/',
  path: '/arrplan/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRegistrationsRoute = UsersRegistrationsRouteImport.update({
  id: '/users/registrations',
  path: '/users/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const UserNameRoute = UserNameRouteImport.update({
  id: '/user/$name',
  path: '/user/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinterSisteRoute = PrinterSisteRouteImport.update({
  id: '/printer/siste',
  path: '/printer/siste',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinterFakturereRoute = PrinterFakturereRouteImport.update({
  id: '/printer/fakturere',
  path: '/printer/fakturere',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupNameRoute = GroupNameRouteImport.update({
  id: '/group/$name',
  path: '/group/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const BukkerIdRoute = BukkerIdRouteImport.update({
  id: '/bukker/$id',
  path: '/bukker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRegisterRoute = BooksRegisterRouteImport.update({
  id: '/books/register',
  path: '/books/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrplanSemesterRoute = ArrplanSemesterRouteImport.update({
  id: '/arrplan/$semester',
  path: '/arrplan/$semester',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatmenyIcsRoute = ApiMatmenyIcsRouteImport.update({
  id: '/api/matmeny-ics',
  path: '/api/matmeny-ics',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdIndexRoute = BooksIdIndexRouteImport.update({
  id: '/books/$id/',
  path: '/books/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatmenyIndexRoute = ApiMatmenyIndexRouteImport.update({
  id: '/api/matmeny/',
  path: '/api/matmeny/',
  getParentRoute: () => rootRouteImport,
} as any)
const DugnadenOldListRoute = DugnadenOldListRouteImport.update({
  id: '/dugnaden/old/list',
  path: '/dugnaden/old/list',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdEditRoute = BooksIdEditRouteImport.update({
  id: '/books/$id/edit',
  path: '/books/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaml2SlsRoute = ApiSaml2SlsRouteImport.update({
  id: '/api/saml2/sls',
  path: '/api/saml2/sls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaml2MetadataRoute = ApiSaml2MetadataRouteImport.update({
  id: '/api/saml2/metadata',
  path: '/api/saml2/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaml2LogoutRoute = ApiSaml2LogoutRouteImport.update({
  id: '/api/saml2/logout',
  path: '/api/saml2/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaml2LoginRoute = ApiSaml2LoginRouteImport.update({
  id: '/api/saml2/login',
  path: '/api/saml2/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaml2AcsRoute = ApiSaml2AcsRouteImport.update({
  id: '/api/saml2/acs',
  path: '/api/saml2/acs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatmenyPlainRoute = ApiMatmenyPlainRouteImport.update({
  id: '/api/matmeny/plain',
  path: '/api/matmeny/plain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/googleapps': typeof GoogleappsRoute
  '/groups': typeof GroupsRoute
  '/matmeny': typeof MatmenyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/matmeny-ics': typeof ApiMatmenyIcsRoute
  '/arrplan/$semester': typeof ArrplanSemesterRoute
  '/books/register': typeof BooksRegisterRoute
  '/bukker/$id': typeof BukkerIdRoute
  '/group/$name': typeof GroupNameRoute
  '/printer/fakturere': typeof PrinterFakturereRoute
  '/printer/siste': typeof PrinterSisteRoute
  '/user/$name': typeof UserNameRoute
  '/users/registrations': typeof UsersRegistrationsRoute
  '/arrplan/': typeof ArrplanIndexRoute
  '/books/': typeof BooksIndexRoute
  '/bukker/': typeof BukkerIndexRoute
  '/users/': typeof UsersIndexRoute
  '/api/matmeny/plain': typeof ApiMatmenyPlainRoute
  '/api/saml2/acs': typeof ApiSaml2AcsRoute
  '/api/saml2/login': typeof ApiSaml2LoginRoute
  '/api/saml2/logout': typeof ApiSaml2LogoutRoute
  '/api/saml2/metadata': typeof ApiSaml2MetadataRoute
  '/api/saml2/sls': typeof ApiSaml2SlsRoute
  '/books/$id/edit': typeof BooksIdEditRoute
  '/dugnaden/old/list': typeof DugnadenOldListRoute
  '/api/matmeny/': typeof ApiMatmenyIndexRoute
  '/books/$id/': typeof BooksIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/googleapps': typeof GoogleappsRoute
  '/groups': typeof GroupsRoute
  '/matmeny': typeof MatmenyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/matmeny-ics': typeof ApiMatmenyIcsRoute
  '/arrplan/$semester': typeof ArrplanSemesterRoute
  '/books/register': typeof BooksRegisterRoute
  '/bukker/$id': typeof BukkerIdRoute
  '/group/$name': typeof GroupNameRoute
  '/printer/fakturere': typeof PrinterFakturereRoute
  '/printer/siste': typeof PrinterSisteRoute
  '/user/$name': typeof UserNameRoute
  '/users/registrations': typeof UsersRegistrationsRoute
  '/arrplan': typeof ArrplanIndexRoute
  '/books': typeof BooksIndexRoute
  '/bukker': typeof BukkerIndexRoute
  '/users': typeof UsersIndexRoute
  '/api/matmeny/plain': typeof ApiMatmenyPlainRoute
  '/api/saml2/acs': typeof ApiSaml2AcsRoute
  '/api/saml2/login': typeof ApiSaml2LoginRoute
  '/api/saml2/logout': typeof ApiSaml2LogoutRoute
  '/api/saml2/metadata': typeof ApiSaml2MetadataRoute
  '/api/saml2/sls': typeof ApiSaml2SlsRoute
  '/books/$id/edit': typeof BooksIdEditRoute
  '/dugnaden/old/list': typeof DugnadenOldListRoute
  '/api/matmeny': typeof ApiMatmenyIndexRoute
  '/books/$id': typeof BooksIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/googleapps': typeof GoogleappsRoute
  '/groups': typeof GroupsRoute
  '/matmeny': typeof MatmenyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/matmeny-ics': typeof ApiMatmenyIcsRoute
  '/arrplan/$semester': typeof ArrplanSemesterRoute
  '/books/register': typeof BooksRegisterRoute
  '/bukker/$id': typeof BukkerIdRoute
  '/group/$name': typeof GroupNameRoute
  '/printer/fakturere': typeof PrinterFakturereRoute
  '/printer/siste': typeof PrinterSisteRoute
  '/user/$name': typeof UserNameRoute
  '/users/registrations': typeof UsersRegistrationsRoute
  '/arrplan/': typeof ArrplanIndexRoute
  '/books/': typeof BooksIndexRoute
  '/bukker/': typeof BukkerIndexRoute
  '/users/': typeof UsersIndexRoute
  '/api/matmeny/plain': typeof ApiMatmenyPlainRoute
  '/api/saml2/acs': typeof ApiSaml2AcsRoute
  '/api/saml2/login': typeof ApiSaml2LoginRoute
  '/api/saml2/logout': typeof ApiSaml2LogoutRoute
  '/api/saml2/metadata': typeof ApiSaml2MetadataRoute
  '/api/saml2/sls': typeof ApiSaml2SlsRoute
  '/books/$id/edit': typeof BooksIdEditRoute
  '/dugnaden/old/list': typeof DugnadenOldListRoute
  '/api/matmeny/': typeof ApiMatmenyIndexRoute
  '/books/$id/': typeof BooksIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/googleapps'
    | '/groups'
    | '/matmeny'
    | '/register'
    | '/reset-password'
    | '/api/matmeny-ics'
    | '/arrplan/$semester'
    | '/books/register'
    | '/bukker/$id'
    | '/group/$name'
    | '/printer/fakturere'
    | '/printer/siste'
    | '/user/$name'
    | '/users/registrations'
    | '/arrplan/'
    | '/books/'
    | '/bukker/'
    | '/users/'
    | '/api/matmeny/plain'
    | '/api/saml2/acs'
    | '/api/saml2/login'
    | '/api/saml2/logout'
    | '/api/saml2/metadata'
    | '/api/saml2/sls'
    | '/books/$id/edit'
    | '/dugnaden/old/list'
    | '/api/matmeny/'
    | '/books/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/googleapps'
    | '/groups'
    | '/matmeny'
    | '/register'
    | '/reset-password'
    | '/api/matmeny-ics'
    | '/arrplan/$semester'
    | '/books/register'
    | '/bukker/$id'
    | '/group/$name'
    | '/printer/fakturere'
    | '/printer/siste'
    | '/user/$name'
    | '/users/registrations'
    | '/arrplan'
    | '/books'
    | '/bukker'
    | '/users'
    | '/api/matmeny/plain'
    | '/api/saml2/acs'
    | '/api/saml2/login'
    | '/api/saml2/logout'
    | '/api/saml2/metadata'
    | '/api/saml2/sls'
    | '/books/$id/edit'
    | '/dugnaden/old/list'
    | '/api/matmeny'
    | '/books/$id'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/googleapps'
    | '/groups'
    | '/matmeny'
    | '/register'
    | '/reset-password'
    | '/api/matmeny-ics'
    | '/arrplan/$semester'
    | '/books/register'
    | '/bukker/$id'
    | '/group/$name'
    | '/printer/fakturere'
    | '/printer/siste'
    | '/user/$name'
    | '/users/registrations'
    | '/arrplan/'
    | '/books/'
    | '/bukker/'
    | '/users/'
    | '/api/matmeny/plain'
    | '/api/saml2/acs'
    | '/api/saml2/login'
    | '/api/saml2/logout'
    | '/api/saml2/metadata'
    | '/api/saml2/sls'
    | '/books/$id/edit'
    | '/dugnaden/old/list'
    | '/api/matmeny/'
    | '/books/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoogleappsRoute: typeof GoogleappsRoute
  GroupsRoute: typeof GroupsRoute
  MatmenyRoute: typeof MatmenyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiMatmenyIcsRoute: typeof ApiMatmenyIcsRoute
  ArrplanSemesterRoute: typeof ArrplanSemesterRoute
  BooksRegisterRoute: typeof BooksRegisterRoute
  BukkerIdRoute: typeof BukkerIdRoute
  GroupNameRoute: typeof GroupNameRoute
  PrinterFakturereRoute: typeof PrinterFakturereRoute
  PrinterSisteRoute: typeof PrinterSisteRoute
  UserNameRoute: typeof UserNameRoute
  UsersRegistrationsRoute: typeof UsersRegistrationsRoute
  ArrplanIndexRoute: typeof ArrplanIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  BukkerIndexRoute: typeof BukkerIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ApiMatmenyPlainRoute: typeof ApiMatmenyPlainRoute
  ApiSaml2AcsRoute: typeof ApiSaml2AcsRoute
  ApiSaml2LoginRoute: typeof ApiSaml2LoginRoute
  ApiSaml2LogoutRoute: typeof ApiSaml2LogoutRoute
  ApiSaml2MetadataRoute: typeof ApiSaml2MetadataRoute
  ApiSaml2SlsRoute: typeof ApiSaml2SlsRoute
  BooksIdEditRoute: typeof BooksIdEditRoute
  DugnadenOldListRoute: typeof DugnadenOldListRoute
  ApiMatmenyIndexRoute: typeof ApiMatmenyIndexRoute
  BooksIdIndexRoute: typeof BooksIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matmeny': {
      id: '/matmeny'
      path: '/matmeny'
      fullPath: '/matmeny'
      preLoaderRoute: typeof MatmenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/googleapps': {
      id: '/googleapps'
      path: '/googleapps'
      fullPath: '/googleapps'
      preLoaderRoute: typeof GoogleappsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bukker/': {
      id: '/bukker/'
      path: '/bukker'
      fullPath: '/bukker/'
      preLoaderRoute: typeof BukkerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrplan/': {
      id: '/arrplan/'
      path: '/arrplan'
      fullPath: '/arrplan/'
      preLoaderRoute: typeof ArrplanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/registrations': {
      id: '/users/registrations'
      path: '/users/registrations'
      fullPath: '/users/registrations'
      preLoaderRoute: typeof UsersRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$name': {
      id: '/user/$name'
      path: '/user/$name'
      fullPath: '/user/$name'
      preLoaderRoute: typeof UserNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printer/siste': {
      id: '/printer/siste'
      path: '/printer/siste'
      fullPath: '/printer/siste'
      preLoaderRoute: typeof PrinterSisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printer/fakturere': {
      id: '/printer/fakturere'
      path: '/printer/fakturere'
      fullPath: '/printer/fakturere'
      preLoaderRoute: typeof PrinterFakturereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$name': {
      id: '/group/$name'
      path: '/group/$name'
      fullPath: '/group/$name'
      preLoaderRoute: typeof GroupNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bukker/$id': {
      id: '/bukker/$id'
      path: '/bukker/$id'
      fullPath: '/bukker/$id'
      preLoaderRoute: typeof BukkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/register': {
      id: '/books/register'
      path: '/books/register'
      fullPath: '/books/register'
      preLoaderRoute: typeof BooksRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrplan/$semester': {
      id: '/arrplan/$semester'
      path: '/arrplan/$semester'
      fullPath: '/arrplan/$semester'
      preLoaderRoute: typeof ArrplanSemesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matmeny-ics': {
      id: '/api/matmeny-ics'
      path: '/api/matmeny-ics'
      fullPath: '/api/matmeny-ics'
      preLoaderRoute: typeof ApiMatmenyIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id/': {
      id: '/books/$id/'
      path: '/books/$id'
      fullPath: '/books/$id/'
      preLoaderRoute: typeof BooksIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matmeny/': {
      id: '/api/matmeny/'
      path: '/api/matmeny'
      fullPath: '/api/matmeny/'
      preLoaderRoute: typeof ApiMatmenyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dugnaden/old/list': {
      id: '/dugnaden/old/list'
      path: '/dugnaden/old/list'
      fullPath: '/dugnaden/old/list'
      preLoaderRoute: typeof DugnadenOldListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id/edit': {
      id: '/books/$id/edit'
      path: '/books/$id/edit'
      fullPath: '/books/$id/edit'
      preLoaderRoute: typeof BooksIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saml2/sls': {
      id: '/api/saml2/sls'
      path: '/api/saml2/sls'
      fullPath: '/api/saml2/sls'
      preLoaderRoute: typeof ApiSaml2SlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saml2/metadata': {
      id: '/api/saml2/metadata'
      path: '/api/saml2/metadata'
      fullPath: '/api/saml2/metadata'
      preLoaderRoute: typeof ApiSaml2MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saml2/logout': {
      id: '/api/saml2/logout'
      path: '/api/saml2/logout'
      fullPath: '/api/saml2/logout'
      preLoaderRoute: typeof ApiSaml2LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saml2/login': {
      id: '/api/saml2/login'
      path: '/api/saml2/login'
      fullPath: '/api/saml2/login'
      preLoaderRoute: typeof ApiSaml2LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saml2/acs': {
      id: '/api/saml2/acs'
      path: '/api/saml2/acs'
      fullPath: '/api/saml2/acs'
      preLoaderRoute: typeof ApiSaml2AcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matmeny/plain': {
      id: '/api/matmeny/plain'
      path: '/api/matmeny/plain'
      fullPath: '/api/matmeny/plain'
      preLoaderRoute: typeof ApiMatmenyPlainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoogleappsRoute: GoogleappsRoute,
  GroupsRoute: GroupsRoute,
  MatmenyRoute: MatmenyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiMatmenyIcsRoute: ApiMatmenyIcsRoute,
  ArrplanSemesterRoute: ArrplanSemesterRoute,
  BooksRegisterRoute: BooksRegisterRoute,
  BukkerIdRoute: BukkerIdRoute,
  GroupNameRoute: GroupNameRoute,
  PrinterFakturereRoute: PrinterFakturereRoute,
  PrinterSisteRoute: PrinterSisteRoute,
  UserNameRoute: UserNameRoute,
  UsersRegistrationsRoute: UsersRegistrationsRoute,
  ArrplanIndexRoute: ArrplanIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  BukkerIndexRoute: BukkerIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ApiMatmenyPlainRoute: ApiMatmenyPlainRoute,
  ApiSaml2AcsRoute: ApiSaml2AcsRoute,
  ApiSaml2LoginRoute: ApiSaml2LoginRoute,
  ApiSaml2LogoutRoute: ApiSaml2LogoutRoute,
  ApiSaml2MetadataRoute: ApiSaml2MetadataRoute,
  ApiSaml2SlsRoute: ApiSaml2SlsRoute,
  BooksIdEditRoute: BooksIdEditRoute,
  DugnadenOldListRoute: DugnadenOldListRoute,
  ApiMatmenyIndexRoute: ApiMatmenyIndexRoute,
  BooksIdIndexRoute: BooksIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
