name: app
on:
  workflow_dispatch:
  push:
    paths:
      - "app/**"
      - ".github/workflows/app.yml"
jobs:
  app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: app/package.json

      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm build

      - run: pnpm exec playwright install --with-deps chromium
      - run: pnpm test:e2e
        env:
          FBS_TEST_USERNAME: halvargimnes
          FBS_TEST_PASSWORD: ${{ secrets.FBS_TEST_PASSWORD }}
      - uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: playwright-report
          path: app/playwright-report/
          retention-days: 7

      - name: Build container
        uses: docker/build-push-action@v6
        with:
          context: app
          load: true
          tags: ghcr.io/blindern/intern-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container
        if: github.ref == 'refs/heads/main'
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: app
          push: true
          tags: ghcr.io/blindern/intern-app:latest

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          curl -sS -i -N -L -H "authorization: bearer $DEPLOYER_TOKEN" -H "content-type: application/json" -X POST "https://deployer.foreningenbs.no/deploy?stream" -d '
          {
            "service": "intern",
            "attributes": {
              "app_image": "ghcr.io/blindern/intern-app@${{ steps.docker_build.outputs.digest }}"
            }
          }' | tee /tmp/deploy-output.txt
          tail -1 /tmp/deploy-output.txt | grep -q "DEPLOY OK"
        env:
          DEPLOYER_TOKEN: ${{ secrets.DEPLOYER_TOKEN }}
